.TH ARGV 1
.SH NAME
argv \-\- print argument list
.SH SYNOPSIS
.B argv
[\fIstring\fR \fI...\fR]
.SH DESCRIPTION
.B argv
writes the argument list starting with the program name
line by line to the standard output.
each line starts with the index followed by a tab and the argument.
.SH SEE ALSO
echo(1)
